name: OpenRP
version: 2.1.2f1

description: Open-source powerful Roleplaying Engine & API for Spigot.
author: darwj
authors:
- darwj
- theatrekids
website: http://www.untold-potential.eu

main: openrp.OpenRP
api-version: 1.13
soft-depend:
- PlaceholderAPI
- MVdWPlaceholderAPI

commands:
   openrp:
      description: OpenRP Utility Command.
      aliases:
      - orp
   character:
      description: Change information about your character!
      aliases:
      - char
   roll:
      description: Roll the dice!
   roleplaytime:
      description: Manage the roleplaying time!
      aliases:
      - rptime