name: OpenRP
version: 2.3.5

description: Open-source powerful Roleplaying Engine & API for Spigot.
authors:
- darwj
- Tanguygab
website: http://www.untold-potential.eu

main: openrp.OpenRP
api-version: 1.13
softdepend:
- PlaceholderAPI

commands:
   openrp:
      description: OpenRP Utility Command.
      aliases:
      - orp
   channeltoggle:
      description: Toggle a channel on or off!
      aliases:
      - chtoggle
      - chtg
   channelswitch:
      description: Switch to a different channel!
      aliases:
      - chswitch
      - chsw
   character:
      description: Change information about your character!
      aliases:
      - char
   roll:
      description: Roll the dice!
   roleplaytime:
      description: Manage the roleplaying time!
      aliases:
      - rptime