# OpenRP Chat

# Permission to bypass the "cooldown" value of each channel.
bypass-cooldown-perm: orpchat.bypasscooldown

# This is used if you type something in chat with no command. 
# Remove this line to not have this feature.
default: in-character

channels:
   
   # In the default config, there are several channels added
   # You can add your own custom channels according to this guide (+ FAQ!):
   # https://github.com/fishydarwin/OpenRP/wiki/%5B2%5D-OpenRP-Chat.-How-do-I-set-it-up%3F
   
   in-character:
      display-name: In Character Chat
      commands: []
      use-perm: orpchat.default
      read-perm: orpchat.default
      color-code-perm: orpchat.usecolors
      format: '&e{player} &fwould say: "{message}&f"'
      range: 15
      cooldown: 3
      action:
         symbol: '*'
         replacement:
            outside-of-actions: '&f'
            for-actions: '&e*'
            
   local-out-of-character:
      display-name: Local OOC
      commands:
      - looc
      - l
      - local
      use-perm: orpchat.default
      read-perm: orpchat.default
      color-code-perm: orpchat.usecolors
      format: '&e[L] &f{player}&8: &7{message}'
      range: 15
      cooldown: 3
      
   out-of-character:
      display-name: OOC
      commands:
      - ooc
      - g
      - global
      use-perm: orpchat.default
      read-perm: orpchat.default
      color-code-perm: orpchat.usecolors
      format: '&6[G] &f{player}&8: &7{message}'
      range: 15
      cooldown: 3
      
   action:
      display-name: Action
      commands:
      - me
      use-perm: orpchat.default
      read-perm: orpchat.default
      color-code-perm: orpchat.usecolors
      format: '&e* &f{player} &e{message}'
      range: 15
      cooldown: 3
      
#  custom-channel-example:
#     display-name: Example Channel
#     commands:
#     - example
#     use-perm: custom.use.perm
#     read-perm: custom.read.perm
#     color-code-perm: example.color.code.perm
#     format: '&a[Example Chat] {player} {message}'
#     range: 42
#     cooldown: 42
#     action:
#        symbol: '*'
#        replacement:
#           outside-of-actions: '&f'
#           for-actions: '&e*'