# OpenRP Chat

bypass-cooldown-perm: orpchat.bypasscooldown

# This is used if you type something in chat with no command. 
# Set to null or remove this line to not have this feature.
default: in-character

channels:
   # example channels: IC and LOOC. Feel free to add as many using this exact format and spacing.
   in-character:
      display-name: In Character Chat
      commands: []
      use-perm: orpchat.default
      read-perm: orpchat.default
      color-code-perm: orpchat.usecolors
      format: '[IC] &e{player} &fwould say: "{message}&f"'
      range: 15
      cooldown: 3
   local-out-of-character:
      display-name: Local OOC
      commands:
      - looc
      - l
      - local
      use-perm: orpchat.default
      read-perm: orpchat.default
      color-code-perm: orpchat.usecolors
      format: '&e[L] &f{player}&8: &7{message}'
      range: 15
      cooldown: 3
#  new-channel-example-give-it-any-name:
#     display-name: example channel
#     commands:
#     - example
#     use-perm: example.use.perm
#     read-perm: example.read.perm
#     color-code-perm: example.color.code.perm
#     format: '&a[Example Chat] {player} {message}'
#     range: 42
#     cooldown: 42