# OpenRP Rolls

use-perm: orprolls.use
alternative-rolls-use-perm: orprolls.alt

# What the default roll is.
default-rolls:
   min: 1
   max: 100
   
# What the min-max output rolls are.   
alternative-rolls:
   min: 1
   max: 200
   
message:
   # What the output looks like in chat.
   text: '&e{player} &7rolled a &6{roll} &7out of {max}.'
   # Remove "range" to have no range.
   range: 15