# OpenRP Descriptions

# Permission for /character set
use-perm: orpdesc.set

# Permission for /character override
override-perm: orpdesc.override

# Permission for /character check
check-perm: orpdesc.check

# Permission to bypass the "cooldown" value of all fields.
bypass-cooldown-perm: orpdesc.bypasscooldown

# Permission for /character profile
profile-perm: orpdesc.profile

# Max amount of profiles players should use, -1 for unlimited
max-profiles: 5

# Permission to bypass max-profiles
bypass-max-profiles-perm: orpdesc.bypassmaxprofiles

fields:

   # In the default config, there are several fields added
   # You can add your own custom fields according to this guide (+ FAQ!):
   # https://github.com/fishydarwin/OpenRP/wiki/%5B3%5D-OpenRP-Descriptions.-How-do-I-set-it-up%3F

   name:
      allowed-values:
         type: contains
         case-sensitive: false
         value: "abcdefghijklmnopqrstuvwxyz.-'' "
      length:
         minimum: 3
         maximum: 24
      color-code-perm: orpdesc.name.color
      cooldown: 10
      default-value: <?>
      
   description:
      allowed-values:
         type: without
         case-sensitive: false
         value: null
      length:
         minimum: 3
      color-code-perm: orpdesc.desc.color
      cooldown: 10
      default-value: No description set
      
   gender:
      allowed-values:
         type: list
         case-sensitive: true
         value:
         - Male
         - Female
         - Other
      color-code-perm: orpdesc.desc.color
      cooldown: 10
      default-value: Other
      
   race:
      allowed-values:
         type: locked
      default-value: Human

# Can a player be right clicked for you to see their description?
right-click-player-to-view-description: true

# Do players have to crouch in order to be able to right click a player for their description?
must-crouch-to-view-description: true

# What does the description look like when a player is right-clicked?
description-format:
- '&e{player}''s &aDescription:'
- '&bName: {orpdesc_name}'
- '&bGender: {orpdesc_gender}'
- '&bRace: {orpdesc_race}'
- '&bDescription:'
- '&f{orpdesc_description}'